// 3D device showcase videos (three.js). Every theme accepts any device model
// through device.model, and any layout through `layout`.
export default {
  turntable: {
    id: 'turntable',
    name: 'Turntable',
    blurb: 'Studio grey sweep. The phone spins in, settles, and sways while screens and captions change.',
    layout: 'turntable',
    palette: { bg: '#e9eaee', bg2: '#ffffff', bg3: '#d5d8e0', ink: '#0e0f13', sub: 'rgba(14,15,19,0.6)', accent: '#3b5bfd', accent2: '#00b3a6' },
    type: { display: 'inter', body: 'inter', weight: 750, tracking: -0.045, size: 1.05, highlight: 'color' },
    background: { kind: 'radial', cx: 50, cy: 55, grain: 0.03, vignette: 0.12 },
    device: { model: 'iphone-17-pro', y: 0.62, size: 0.66, glare: 0.5 },
    scene: { env: 1.1, wall: { depth: 0.08, opacity: 0.22 }, key: { dir: [-0.4, 0.9, 1] } },
    motion: { duration: 10, spins: 1.5 },
  },

  orbit: {
    id: 'orbit',
    name: 'Orbit',
    blurb: 'Low-key drama. The camera arcs around a tilted phone while a coloured rim light slides along its edge.',
    layout: 'orbit',
    palette: { bg: '#030306', bg2: '#10101c', bg3: '#26204a', ink: '#ffffff', sub: 'rgba(255,255,255,0.65)', accent: '#a78bfa', accent2: '#f472b6' },
    type: { display: 'sora', body: 'inter', weight: 600, tracking: -0.04, size: 1.02, highlight: 'gradient' },
    background: { kind: 'radial', cx: 50, cy: 42, grain: 0.06, vignette: 0.55 },
    device: { model: 'iphone-17-pro-max', y: 0.41, size: 0.6, pose: [10, -12, 6], finish: '#34343c', glare: 0.9 },
    scene: {
      env: 0.8,
      ambient: 0.15,
      rims: [{ color: '#a78bfa', intensity: 5, dir: [1, 0.4, -0.6] }, { color: '#f472b6', intensity: 3, dir: [-1, -0.2, -0.5] }],
      wall: null,
    },
    motion: { duration: 10, arc: 56 },
  },

  float: {
    id: 'float',
    name: 'Float',
    blurb: 'Weightless pastel. The phone drifts with glossy orbs around it; a loop-friendly product clip.',
    layout: 'float',
    palette: { bg: '#fde2f3', bg2: '#d7e3ff', bg3: '#fff4d6', ink: '#1c1b3a', sub: 'rgba(28,27,58,0.65)', accent: '#6c63ff', accent2: '#ff8fab' },
    type: { display: 'fraunces', body: 'manrope', weight: 500, tracking: -0.02, size: 1.05, highlight: 'italic', italicFont: 'fraunces' },
    background: { kind: 'aurora', blend: 'normal', intensity: 0.6, grain: 0.05 },
    device: { model: 'iphone-17-pro', y: 0.63, size: 0.64, pose: [6, -18, 6], float: 1, finish: '#e8e2f5' },
    scene: { wall: { depth: 0.12, opacity: 0.18 }, shadow: { blur: 28 } },
    decor: [{ kind: 'orbs', count: 5, finish: 'glossy', size: 0.1, colors: ['#6c63ff', '#ff8fab', '#ffffff'], seed: 6 }],
    motion: { duration: 10 },
  },

  rise: {
    id: 'rise',
    name: 'Rise',
    blurb: 'Hero entrance: the phone rises and turns into place, then the camera slowly pushes into the screen.',
    layout: 'rise',
    palette: { bg: '#0b1d3a', bg2: '#16487a', bg3: '#2dd4bf', ink: '#ffffff', sub: 'rgba(255,255,255,0.72)', accent: '#5eead4', accent2: '#fde047' },
    type: { display: 'jakarta', body: 'jakarta', weight: 800, tracking: -0.04, size: 1.05, highlight: 'color' },
    background: { kind: 'gradient', angle: 170, pattern: 'waves', patternOpacity: 0.07, patternDrift: 3, grain: 0.04 },
    device: { model: 'iphone-17-pro', y: 0.62, size: 0.66, finish: '#1f3b5c' },
    scene: { wall: { depth: 0.1, opacity: 0.35 }, rims: [{ color: '#5eead4', intensity: 2.5, dir: [1, 0.3, -0.5] }] },
    motion: { duration: 10, push: 0.86 },
  },

  flip: {
    id: 'flip',
    name: 'Flip reveal',
    blurb: 'Starts on the camera bump, flips to reveal the screen under a warm spotlight.',
    layout: 'flip',
    palette: { bg: '#120c08', bg2: '#3a2414', bg3: '#ffb86b', ink: '#fff8ef', sub: 'rgba(255,248,239,0.7)', accent: '#ffb86b', accent2: '#ff7a59' },
    type: { display: 'dm-serif', body: 'inter', weight: 400, tracking: -0.01, size: 1.15, highlight: 'italic', italicFont: 'dm-serif' },
    background: { kind: 'spotlight', cy: 18, beam: 0.25, grain: 0.06, vignette: 0.45 },
    device: { model: 'iphone-17-pro', y: 0.62, size: 0.66, finish: '#e07a3a', glare: 0.7 },
    scene: { key: { color: '#ffd9b0', intensity: 2.6 }, rims: [{ color: '#ff7a59', intensity: 3, dir: [1, 0.2, -0.6] }], wall: { depth: 0.1, opacity: 0.4 } },
    motion: { duration: 9 },
  },

  trio: {
    id: 'trio',
    name: 'Trio',
    blurb: 'Cross-platform line-up: Galaxy, iPhone and Pro Max rise in sequence and fan out, each on its own screen.',
    layout: 'trio',
    palette: { bg: '#0c0a1d', bg2: '#27205c', bg3: '#0f4c5c', ink: '#ffffff', sub: 'rgba(255,255,255,0.7)', accent: '#facc15', accent2: '#fb7185' },
    type: { display: 'outfit', body: 'outfit', weight: 700, tracking: -0.035, size: 1.02, highlight: 'gradient' },
    background: { kind: 'mesh', grain: 0.05, vignette: 0.3, seed: 31 },
    devices: ['galaxy-s21-ultra', 'iphone-17-pro', 'iphone-17-pro-max'],
    device: { y: 0.65, size: 0.52 },
    scene: { wall: { depth: 0.1, opacity: 0.35 } },
    motion: { duration: 10 },
  },

  desk: {
    id: 'desk',
    name: 'Desk',
    blurb: 'Web + mobile: the MacBook lid opens, the camera settles, a phone slides in beside it.',
    layout: 'desk',
    samples: 'desk',
    palette: { bg: '#f4efe8', bg2: '#e7dccd', bg3: '#cbb89d', ink: '#1f1a14', sub: 'rgba(31,26,20,0.65)', accent: '#b45309', accent2: '#0f766e' },
    type: { display: 'instrument-serif', body: 'inter', weight: 400, tracking: -0.01, size: 0.95, highlight: 'italic', italicFont: 'instrument-serif' },
    text: { margin: 0.04 },
    background: { kind: 'radial', cx: 50, cy: 70, grain: 0.05 },
    device: { phone: { pose: [0, -19, 0] } },
    motion: { duration: 10 },
  },

  spotlight: {
    id: 'spotlight',
    name: 'Spotlight 360',
    blurb: 'A full turn on a mirror floor under a single beam. Classic keynote energy.',
    layout: 'spotlight',
    palette: { bg: '#020203', bg2: '#15161b', bg3: '#ffffff', ink: '#ffffff', sub: 'rgba(255,255,255,0.62)', accent: '#e5e7eb', accent2: '#9ca3af' },
    type: { display: 'space-grotesk', body: 'inter', weight: 600, tracking: -0.04, size: 1.02, highlight: 'color' },
    background: { kind: 'spotlight', cy: 8, beam: 0.22, grain: 0.05, vignette: 0.5 },
    device: { model: 'iphone-17-pro-max', y: 0.56, size: 0.6, finish: '#3a3a40', glare: 0.9 },
    scene: { floor: { y: 0.86, mirror: 0.45, opacity: 0.55 }, wall: null, key: { dir: [-0.15, 1, 0.4], intensity: 2.8 }, camera: { pitch: 7 } },
    motion: { duration: 10 },
  },

  synthwave: {
    id: 'synthwave',
    name: 'Synthwave',
    blurb: 'Neon float over a scrolling retro grid, magenta and cyan rims, drifting 3D toys.',
    layout: 'float',
    palette: { bg: '#0d0221', bg2: '#2a0845', bg3: '#ff2a6d', ink: '#ffffff', sub: 'rgba(255,255,255,0.75)', accent: '#05d9e8', accent2: '#ff2a6d' },
    type: { display: 'unbounded', body: 'space-grotesk', weight: 800, tracking: -0.03, size: 0.95, highlight: 'outline', shadow: 0.5 },
    background: { kind: 'synth', speed: 1.2 },
    device: { model: 'galaxy-s21-ultra', y: 0.62, size: 0.62, pose: [8, -18, 5], float: 1.2 },
    scene: { rims: [{ color: '#ff2a6d', intensity: 4, dir: [1, 0.3, -0.5] }, { color: '#05d9e8', intensity: 3.5, dir: [-1, 0.2, -0.4] }], wall: { depth: 0.1, opacity: 0.4 } },
    decor: [{ kind: 'shapes', count: 4, shapes: ['knot', 'cube', 'ring', 'pill'], colors: ['#05d9e8', '#ff2a6d', '#ffffff'], size: 0.12, seed: 2 }],
    motion: { duration: 10, intro: true, outro: true },
  },

  keyframes: {
    id: 'keyframes',
    name: 'Keyframes',
    blurb: 'Your own choreography. Pose the device and camera at points along the timeline in the studio, or write motion.keys by hand.',
    layout: 'keyframes',
    palette: { bg: '#0b0d12', bg2: '#1b2030', bg3: '#2d3550', ink: '#ffffff', sub: 'rgba(255,255,255,0.68)', accent: '#c6ff3d', accent2: '#8b7bff' },
    type: { display: 'space-grotesk', body: 'inter', weight: 650, tracking: -0.04, size: 1, highlight: 'color' },
    background: { kind: 'radial', cx: 50, cy: 58, grain: 0.05, vignette: 0.35 },
    device: { model: 'iphone-17-pro', y: 0.62, size: 0.64, glare: 0.7 },
    scene: { env: 0.9, ambient: 0.25, rims: [{ color: '#8b7bff', intensity: 3, dir: [1, 0.3, -0.6] }], wall: { depth: 0.1, opacity: 0.3 } },
    motion: { duration: 10 },
  },
}
